### ISSUE TITLE
Drag and Drop in Safari is opening up File in Same Window.

### ISSUE THREAD

**Issue by praveen33in** [georgipeltekov/ngx-file-drop#20] opened 2017-11-03 21:05 UTC
ngx-file-drop is working good in all browsers except Safari. 
Unlike other browsers, when we drag and drop a file in Safari (MacBook), the file is opening in the same window. 
Safari version# 9
ngx-file-drop# 1.0.12

Note, i have also tried drag and drop in Demo link provided, in Safari, and its opening up the file.

**Comment by georgipeltekov** [comment] 2017-11-04 12:32
duplicate of #6

**Closed by georgipeltekov** 2017-11-04 12:32 UTC
Labels: duplicate
