### ISSUE TITLE
More files than 100 in a directory

### ISSUE THREAD

**Issue by doananhbao94** [georgipeltekov/ngx-file-drop#4] opened 2017-08-20 08:16 UTC
Hi sir @georgipeltekov ,  
I have a problem when used your lib.
I see the entries only have max files are 100, if i drag folder have more than the maximum it can read more 100 files. How can i fix it?

Thank you.

**Comment by georgipeltekov** [comment] 2017-08-20 08:52
Did you try to drag the folder on the demo page:
https://georgipeltekov.github.io/

I just drag a huge folder and as you can see there are 110 pages (10 entries each)
https://ibb.co/mshNP5

**Comment by doananhbao94** [comment] 2017-08-20 09:07
I have drag 185 items and the result here sir:

https://ibb.co/bRATWk
https://ibb.co/n6q6HQ

i don't know why. I have debugged, i see the entries.length only 100 files. no more.

**Comment by georgipeltekov** [comment] 2017-08-20 09:14
I cannot reproduce your problem. I tried both dragging more than 100 files and a folders with a lot of files in them, both cases works as expected. Can you try with different browsers? If you don't provide working example of how to reproduce the issue there is nothing much I can do.

**Comment by doananhbao94** [comment] 2017-08-20 09:20
This problem only in chrome sir @georgipeltekov  :(.
How can i fix it?

**Comment by georgipeltekov** [comment] 2017-08-20 09:27
Are you sure? I just tested with the latest Chrome version and it is working fine. You can try to update your chrome browser and try again.

**Comment by doananhbao94** [comment] 2017-08-20 09:31
Yes I am, my version chrome is Version 60.0.3112.101 (Official Build) (64-bit).
Or all of this file is same extensions so it only read 100 files?

**Comment by georgipeltekov** [comment] 2017-08-20 09:41
I tried with 200 files of same extensions and again, it is working fine. Please check whether there is something specific with the missing files. I mean which files are getting uploaded and which not. Only the first 100 or the order is different?  Did you tried with some other folders?
Again, if there is no working example of how to reproduce the issues, there is nothing much I can do.

**Comment by georgipeltekov** [comment] 2017-08-20 15:43
closing as not-reproducible

**Closed by georgipeltekov** 2017-08-20 15:43 UTC
Labels: invalid

**Comment by jpinxten** [comment] 2017-10-19 14:14
@georgipeltekov This issue should not be closed. 

The reason this happens is because when its a directory, you call dirReader.readEntries() only 1 time, you need to keep calling it till you get no more results.

Here is a code example: https://www.html5rocks.com/en/tutorials/file/filesystem/#toc-dir-reading

**Comment by georgipeltekov** [comment] 2017-10-19 14:33
Thank you very much for pointing this out. I just released a new version with the fix. Please let me know if it is ok now.

**Comment by jpinxten** [comment] 2017-10-19 14:52
I think you popToStack() get called to many times now
